### PR TITLE
feat: add python sdk connection guidance

### PR DESCRIPTION
**Pull request by hezean**

### CODE REVIEW

**Comment by FengShang** [comment]
Please Fix the Codacy Static Code Analysis warnings first.

**Comment by hezean** [comment]
Hi @FengShang, that may be a false positive, the build ci also passed
Screen Shot 2022-08-24 at 15 12 38

as for the code style which it suggests changing `'` to `"`, I think it's better to be consistent with the existing code?

**Comment by FengShang** [comment]
> Hi @FengShang, that may be a false positive, the build ci also passed Screen Shot 2022-08-24 at 15 12 38
> 
> as for the code style which it suggests changing `'` to `"`, I think it's better to be consistent with the existing code?

OK，go ahead~.

**Comment by FengShang** [comment]
Still need to resolve conflict, sorry I'm changing the same file.

**Comment by hezean** [comment]
PTAL @FengShang, this pr is ready to merge

**Comment by frankzhaopeng** [comment]
Some problems are found and I fixed them in my branch, will be merge afternoon.

- Function getPythonCode should use serverSdkKey not clientSdkKey
- String userWithCode needs adding linefeed when multiple custom attributes are set, can you help to check whether the code below is correct? @HeZean @dengfeige 

image

**Comment by hezean** [comment]
Yeah that's correct, sorry for the oversight

**Pull request merged**
