### PR TITLE
fix: add i18n (zh) for condition types

### LINKED ISSUE #35: The condition types of the toggle and segment rules in the Chinese version need to be changed to Chinese.

### PR DESCRIPTION
**Pull request by hezean**
fixes https://github.com/FeatureProbe/FeatureProbe/issues/35

### CODE REVIEW

**Comment by FengShang** [comment]
image

This UI should be changed, to make it more readable. We are going to provide a new UI design later.

**Comment by yuying-Alice** [comment]
图片

**Comment by yuying-Alice** [comment]
@HeZean Here is the PRD of this feature, You can reference this to fix it,UI design will be ready tomorrow.
图片

**Comment by frankzhaopeng** [comment]
@hezean Hi, please resolve conflicts first, I will merge your changes. I will finish the new feature above in next iteration. Thanks a lot.

**Review by hezean — COMMENTED** [review]
@frankzhaopeng PTAL, you can directly commit to my branch if there's any problem

**Comment by hezean** [comment]
Screenshot 2022-12-03 at 16 39 27
Screenshot 2022-12-03 at 16 40 03

**Pull request merged**
